export const FORM_FIELDS = {
  tapeline: [
    { name: 'date', label: 'Date', type: 'date', required: true, colIndex: 1 },
    { name: 'time', label: 'Entry Time', type: 'time', required: true, colIndex: 2 },
    { name: 'code', label: 'Code', type: 'text', required: true, colIndex: 3 },
    { name: 'shift', label: 'Shift', type: 'select', required: true, colIndex: 6, options: ['A', 'B'] },
    { name: 'operator', label: 'Operator Name', type: 'select', required: true, colIndex: 7, options: ['Sunil Singh', 'Mantosh'] },
    { name: 'total_input_kg', label: 'Total Input (kg)', type: 'number', required: true, colIndex: 23 },
    { name: 'start_wastage', label: 'Starting Wastage (kg)', type: 'number', required: false, colIndex: 24 },
    { name: 'run_wastage', label: 'Running Wastage (kg)', type: 'number', required: false, colIndex: 25 },
    { name: 'wastage', label: 'Wastage (kg)', type: 'number', required: false, colIndex: 26 },
    { name: 'pp_invoice', label: 'PP Purchase Invoice No', type: 'text', required: false, colIndex: 27 },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false, colIndex: 28 },
    { name: 'tester_name', label: 'Tester Name', type: 'select', required: true, colIndex: 29, options: ['Umraan', 'Rehaan', 'Datta', 'Ram'] },
    { name: 'no_production', label: 'No Production ?', type: 'checkbox', required: false, colIndex: null },
  ],
  rolldown: [
    { name: 'date', label: 'Date', type: 'date', required: true, colIndex: 4 },
    { name: 'loom_no', label: 'Loom No.', type: 'number', required: true, colIndex: 6 },
    { name: 'shift', label: 'Shift', type: 'select', required: true, colIndex: 12, options: ['A', 'B'] },
    { name: 'roll_no', label: 'Roll No.', type: 'text', required: true, colIndex: 13 },
    { name: 'fabric_mtrs', label: 'Roll Down Fabric (mtrs)', type: 'number', required: true, colIndex: 15 },
    { name: 'net_wt_kg', label: 'Roll Net Wt. (Kg)', type: 'number', required: true, colIndex: 16 },
    { name: 'loom_wastage', label: 'Loom Wastage (Kg)', type: 'number', required: false, colIndex: 20 },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false, colIndex: 21 },
    { name: 'qc_name', label: 'QC Name', type: 'select', required: true, colIndex: 22, options: ['Umraan', 'Rehaan', 'Datta', 'Ram'] },
  ],
  liner: [
    { name: 'date', label: 'Date', type: 'date', required: true, colIndex: 2 },
    { name: 'time', label: 'Entry Time', type: 'time', required: true, colIndex: 3 },
    { name: 'code', label: 'Code', type: 'text', required: true, colIndex: 4 },
    { name: 'shift', label: 'Shift', type: 'select', required: true, colIndex: 8, options: ['A', 'B'] },
    { name: 'operator', label: 'Operator Name', type: 'select', required: true, colIndex: 9, options: ['N.Modi', 'Guddu Singh'] },
    { name: 'machine_no', label: 'Machine No.', type: 'select', required: true, colIndex: 10, options: ['1', '2', '3'] },
    { name: 'liner_cut', label: 'Liner Cut Weight (gms)', type: 'text', required: false, colIndex: 16 },
    { name: 'lldpe_kg', label: 'LLDPE (Kg)', type: 'number', required: false, colIndex: 17 },
    { name: 'filler_kandui', label: 'Filler Kandui (Kg)', type: 'number', required: false, colIndex: 18 },
    { name: 'kandui_mouser', label: 'Kandui Mouser (Kg)', type: 'number', required: false, colIndex: 19 },
    { name: 'rp', label: 'RP', type: 'number', required: false, colIndex: 20 },
    { name: 'mb04', label: 'MB-04', type: 'number', required: false, colIndex: 21 },
    { name: 'ldpe_kg', label: 'LDPE (Kg)', type: 'number', required: false, colIndex: 22 },
    { name: 'tpt_kg', label: 'TPT (Kg)', type: 'number', required: false, colIndex: 23 },
    { name: 'liner_wastage', label: 'Liner Wastage (kg)', type: 'number', required: false, colIndex: 24 },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false, colIndex: 26 },
    { name: 'tester_name', label: 'Tester Name', type: 'select', required: true, colIndex: 27, options: ['Umraan', 'Rehaan', 'Datta', 'Ram'] },
  ],
  printing: [
    { name: 'date', label: 'Date', type: 'date', required: true, colIndex: 2 },
    { name: 'time', label: 'Entry Time', type: 'time', required: true, colIndex: 3 },
    { name: 'shift', label: 'Shift', type: 'select', required: true, colIndex: 8, options: ['A', 'B'] },
    { name: 'machine_name', label: 'Machine Name', type: 'select', required: true, colIndex: 9, options: ['PNRM', 'JP Online'] },
    { name: 'operator', label: 'Operator', type: 'select', required: true, colIndex: 10, options: ['Brijesh', 'Pathak'] },
    { name: 'roll_no', label: 'Roll No.', type: 'text', required: true, colIndex: 12 },
    { name: 'print_wastage', label: 'Printing Wastage (bags)', type: 'number', required: false, colIndex: 16 },
    { name: 'ink_wastage', label: 'Ink Wastage', type: 'number', required: false, colIndex: 17 },
    { name: 'reducer_wastage', label: 'Reducer Wastage', type: 'number', required: false, colIndex: 18 },
    { name: 'test_bags', label: 'Test Printing Bags (Nos)', type: 'number', required: false, colIndex: 19 },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false, colIndex: 21 },
    { name: 'qc_name', label: 'QC Name', type: 'select', required: true, colIndex: 22, options: ['Umraan', 'Rehaan', 'Datta', 'Ram'] },
    { name: 'issue_date', label: 'Date of Issue', type: 'date', required: false, colIndex: 23 },
    { name: 'issue_to_bcs', label: 'Issue to BCS Machine No', type: 'number', required: false, colIndex: 24 },
  ],
  bopp: [
    { name: 'date', label: 'Date', type: 'date', required: true, colIndex: 2 },
    { name: 'time', label: 'Entry Time', type: 'time', required: true, colIndex: 3 },
    { name: 'shift', label: 'Shift', type: 'select', required: true, colIndex: 8, options: ['A', 'B'] },
    { name: 'operator', label: 'Operator Name', type: 'text', required: true, colIndex: 9 },
    { name: 'roll_no', label: 'Roll No.', type: 'text', required: true, colIndex: 11 },
    { name: 'gross_weight', label: 'Gross Weight (Kg)', type: 'number', required: true, colIndex: 13 },
    { name: 'final_lam_mtrs', label: 'Final Laminated Fabric (Mtrs)', type: 'number', required: true, colIndex: 17 },
    { name: 'lam_wastage', label: 'Lamination Wastage (kg)', type: 'number', required: false, colIndex: 18 },
    { name: 'pp_h3050', label: 'PP H3050 EC (Kg)', type: 'number', required: false, colIndex: 19 },
    { name: 'la17', label: 'LA.17.1070 (Kg)', type: 'number', required: false, colIndex: 20 },
    { name: 'r7330', label: '7330 (Kg)', type: 'number', required: false, colIndex: 21 },
    { name: 'uv_kg', label: 'U.V (Kg)', type: 'number', required: false, colIndex: 22 },
    { name: 'kandui_filler', label: 'Kandui Filler (Kg)', type: 'number', required: false, colIndex: 23 },
    { name: 'bopp_rolls_nos', label: 'BOPP Roll Used (Nos)', type: 'number', required: false, colIndex: 24 },
    { name: 'bopp_roll_wt', label: 'BOPP Roll Weight (Kg)', type: 'number', required: false, colIndex: 25 },
    { name: 'bopp_wastage', label: 'BOPP Wastage', type: 'number', required: false, colIndex: 26 },
    { name: 'test_bags', label: 'Test Bags (Nos)', type: 'number', required: false, colIndex: 27 },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false, colIndex: 28 },
    { name: 'qc_name', label: 'QC Name', type: 'select', required: true, colIndex: 29, options: ['Umraan', 'Rehaan', 'Datta', 'Ram'] },
    { name: 'issue_date', label: 'Date of Issue', type: 'date', required: false, colIndex: 30 },
    { name: 'issue_to_bcs', label: 'Issue to BCS Machine No', type: 'number', required: false, colIndex: 31 },
  ],
  bcs: [
    { name: 'date', label: 'Date', type: 'date', required: true, colIndex: 3 },
    { name: 'time', label: 'Entry Time', type: 'time', required: true, colIndex: 4 },
    { name: 'shift', label: 'Shift', type: 'select', required: true, colIndex: 10, options: ['A', 'B'] },
    { name: 'operator', label: 'Operator Name', type: 'select', required: true, colIndex: 11, options: ['Navindu', 'Vikas', 'Ajit'] },
    { name: 'contractor', label: 'Contractor Name', type: 'select', required: true, colIndex: 12, options: ['Ashok Sahani', 'Sujit Yadav'] },
    { name: 'bcs_machine_no', label: 'BCS Machine Number', type: 'number', required: true, colIndex: 13 },
    { name: 'roll_no', label: 'Roll No.', type: 'text', required: true, colIndex: 14 },
    { name: 'bags_produced', label: 'Bags Produced (Nos.)', type: 'number', required: true, colIndex: 16 },
    { name: 'bcs_wastage', label: 'BCS Wastage (Nos)', type: 'number', required: false, colIndex: 18 },
    { name: 'loom_damaged', label: 'Loom Damaged Bags (Nos)', type: 'number', required: false, colIndex: 19 },
    { name: 'print_damaged', label: 'Print/BOPP/Lam Damaged', type: 'number', required: false, colIndex: 20 },
    { name: 'blade_cut', label: 'Blade Cut Damaged (Nos)', type: 'number', required: false, colIndex: 21 },
    { name: 'repairable', label: 'Repairable Bags (Nos)', type: 'number', required: false, colIndex: 22 },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false, colIndex: 25 },
    { name: 'tester_name', label: 'Tester Name', type: 'select', required: true, colIndex: 26, options: ['Umraan', 'Rehaan', 'Datta', 'Ram'] },
  ],
  baling: [
    { name: 'date', label: 'Date', type: 'date', required: true, colIndex: 2 },
    { name: 'time', label: 'Entry Time', type: 'time', required: true, colIndex: 3 },
    { name: 'code', label: 'Code', type: 'text', required: true, colIndex: 4 },
    { name: 'no_of_bale', label: 'No. of Bale', type: 'number', required: true, colIndex: 9 },
    { name: 'extra_bags', label: 'Extra Bags in Bale', type: 'number', required: false, colIndex: 10 },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false, colIndex: 12 },
    { name: 'contractor', label: 'Contractor Name', type: 'select', required: true, colIndex: 13, options: ['Ashok Sahani', 'Sujit Yadav'] },
    { name: 'qc_name', label: 'QC Name', type: 'select', required: true, colIndex: 14, options: ['Umraan', 'Rehaan', 'Datta', 'Ram'] },
  ],
  loom_qc: [
    { name: 'date',               label: 'Date',                      type: 'date',    required: true,  colIndex: 1  },
    { name: 'time',               label: 'Time',                      type: 'time',    required: true,  colIndex: 2  },
    { name: 'code',               label: 'Code',                      type: 'text',    required: true,  colIndex: 3  },
    { name: 'shift',              label: 'Shift',                     type: 'select',  required: true,  colIndex: 8,  options: ['A','B'] },
    { name: 'loom_no',            label: 'Loom No.',                  type: 'number',  required: true,  colIndex: 9  },
    { name: 'operator_name',      label: 'Operator Name',             type: 'text',    required: false, colIndex: 10 },
    { name: 'mesh',               label: 'Mesh (Warp x Weft)',        type: 'text',    required: false, colIndex: 11 },
    { name: 'req_fabric_width',   label: 'Required Fabric Width',     type: 'number',  required: false, colIndex: 12 },
    { name: 'actual_fabric_width',label: 'Actual Fabric Width',       type: 'number',  required: true,  colIndex: 13 },
    { name: 'req_meter_weight',   label: 'Required Meter Weight',     type: 'number',  required: false, colIndex: 14 },
    { name: 'actual_meter_weight',label: 'Actual Meter Weight',       type: 'number',  required: true,  colIndex: 15 },
    { name: 'pass_fail',          label: 'Pass / Fail',               type: 'select',  required: true,  colIndex: 16, options: ['✅ Pass','❌ Fail'] },
    { name: 'remarks',            label: 'Remarks',                   type: 'textarea',required: false, colIndex: 17 },
    { name: 'tester_name',        label: 'Tester Name',               type: 'text',    required: true,  colIndex: 18 },
    { name: 'fail_photo_link',    label: 'Fail Photo Link',           type: 'text',    required: false, colIndex: 19 },
    { name: 'debit',              label: 'Debit',                     type: 'number',  required: false, colIndex: 20 },
  ],
  liner_qc: [
    { name: 'date',               label: 'Date',                      type: 'date',    required: true,  colIndex: 1  },
    { name: 'time',               label: 'Entry Time',                type: 'time',    required: true,  colIndex: 2  },
    { name: 'shift',              label: 'Shift',                     type: 'select',  required: true,  colIndex: 5,  options: ['A','B'] },
    { name: 'operator_name',      label: 'Operator Name',             type: 'text',    required: false, colIndex: 6  },
    { name: 'liner_length',       label: 'Liner Length',              type: 'number',  required: true,  colIndex: 7  },
    { name: 'liner_width',        label: 'Liner Width',               type: 'number',  required: true,  colIndex: 8  },
    { name: 'liner_weight',       label: 'Liner Weight',              type: 'number',  required: true,  colIndex: 9  },
    { name: 'liner_print',        label: 'Liner Print (Y/N)',         type: 'select',  required: true,  colIndex: 10, options: ['Y','N'] },
    { name: 'client_alignment',   label: 'Client Alignment',          type: 'select',  required: false, colIndex: 11, options: ['✅ Pass','❌ Fail'] },
    { name: 'remarks',            label: 'Remark',                    type: 'textarea',required: false, colIndex: 12 },
  ],
  printing_qc: [
    { name: 'date',               label: 'Date',                      type: 'date',    required: true,  colIndex: 1  },
    { name: 'time',               label: 'Time',                      type: 'time',    required: true,  colIndex: 2  },
    { name: 'code',               label: 'Code',                      type: 'text',    required: true,  colIndex: 3  },
    { name: 'shift',              label: 'Shift',                     type: 'select',  required: true,  colIndex: 6,  options: ['A','B'] },
    { name: 'machine_no',         label: 'Machine No.',               type: 'select',  required: true,  colIndex: 7,  options: ['PNRM','JP Online'] },
    { name: 'design_accuracy',    label: 'Design Accuracy',           type: 'select',  required: true,  colIndex: 8,  options: ['✅ Pass','❌ Fail'] },
    { name: 'content_accuracy',   label: 'Content Accuracy',          type: 'select',  required: true,  colIndex: 9,  options: ['✅ Pass','❌ Fail'] },
    { name: 'color_matching',     label: 'Color Matching',            type: 'select',  required: true,  colIndex: 10, options: ['✅ Pass','❌ Fail'] },
    { name: 'bag_length',         label: 'Bag Length',                type: 'number',  required: true,  colIndex: 11 },
    { name: 'bag_width',          label: 'Bag Width',                 type: 'number',  required: true,  colIndex: 12 },
    { name: 'operator_name',      label: 'Operator Name',             type: 'text',    required: false, colIndex: 14 },
    { name: 'contractor_name',    label: 'Contractor Name',           type: 'text',    required: false, colIndex: 15 },
    { name: 'remarks',            label: 'Remarks',                   type: 'textarea',required: false, colIndex: 16 },
    { name: 'tester_name',        label: 'Tester Name',               type: 'text',    required: true,  colIndex: 17 },
    { name: 'fail_photo_link',    label: 'Link (Fail Photo)',         type: 'text',    required: false, colIndex: 18 },
    { name: 'debit',              label: 'Debit',                     type: 'number',  required: false, colIndex: 19 },
  ],
  printing_ink_qc: [
    { name: 'date',               label: 'Date',                      type: 'date',    required: true,  colIndex: 0  },
    { name: 'time',               label: 'Time',                      type: 'time',    required: true,  colIndex: 1  },
    { name: 'code',               label: 'Code',                      type: 'text',    required: true,  colIndex: 2  },
    { name: 'shift',              label: 'Shift',                     type: 'select',  required: true,  colIndex: 6,  options: ['A','B'] },
    { name: 'operator_name',      label: 'Operator Name',             type: 'text',    required: false, colIndex: 7  },
    { name: 'nail_test',          label: 'Nail Test',                 type: 'select',  required: true,  colIndex: 8,  options: ['✅ Pass','❌ Fail'] },
    { name: 'tape_test',          label: 'Tape Test',                 type: 'select',  required: true,  colIndex: 9,  options: ['✅ Pass','❌ Fail'] },
    { name: 'rub_test',           label: 'Rub Test',                  type: 'select',  required: true,  colIndex: 10, options: ['✅ Pass','❌ Fail'] },
    { name: 'qc_name',            label: 'QC Name',                   type: 'text',    required: true,  colIndex: 14 },
    { name: 'remarks',            label: 'Remark',                    type: 'textarea',required: false, colIndex: 15 },
  ],
  bopp_qc: [
    { name: 'date',               label: 'Date',                      type: 'date',    required: true,  colIndex: 1  },
    { name: 'time',               label: 'Time',                      type: 'time',    required: true,  colIndex: 2  },
    { name: 'code',               label: 'Code',                      type: 'text',    required: true,  colIndex: 3  },
    { name: 'shift',              label: 'Shift',                     type: 'select',  required: true,  colIndex: 6,  options: ['A','B'] },
    { name: 'bopp_film_print',    label: 'BOPP Film Print Accuracy',  type: 'select',  required: true,  colIndex: 7,  options: ['✅ Pass','❌ Fail'] },
    { name: 'pasting_test',       label: 'Pasting Test Result',       type: 'select',  required: true,  colIndex: 8,  options: ['✅ Pass','❌ Fail'] },
    { name: 'pasting_accuracy',   label: 'Pasting Accuracy',          type: 'select',  required: true,  colIndex: 9,  options: ['✅ Pass','❌ Fail'] },
    { name: 'visual_defects',     label: 'Visual Defects',            type: 'select',  required: true,  colIndex: 10, options: ['None','Air Bubble','Gaps','Multiple'] },
    { name: 'operator_name',      label: 'Operator Name',             type: 'text',    required: false, colIndex: 11 },
    { name: 'remarks',            label: 'Remarks',                   type: 'textarea',required: false, colIndex: 12 },
    { name: 'qc_name',            label: 'QC Name',                   type: 'text',    required: true,  colIndex: 13 },
  ],
  bcs_qc: [
    { name: 'date',               label: 'Date',                      type: 'date',    required: true,  colIndex: 0  },
    { name: 'time',               label: 'Time',                      type: 'time',    required: true,  colIndex: 1  },
    { name: 'code',               label: 'Code',                      type: 'text',    required: true,  colIndex: 2  },
    { name: 'shift',              label: 'Shift',                     type: 'select',  required: true,  colIndex: 6,  options: ['A','B'] },
    { name: 'machine',            label: 'Machine',                   type: 'number',  required: true,  colIndex: 7  },
    { name: 'cut_length_req',     label: 'Cut Length Required (in)',  type: 'number',  required: false, colIndex: 8  },
    { name: 'cut_length_actual',  label: 'Cut Length Actual (in)',    type: 'number',  required: true,  colIndex: 9  },
    { name: 'stitches_per_4in',   label: 'Number of Stitches (per 4 inch)', type: 'number', required: true, colIndex: 10 },
    { name: 'bottom_stitching',   label: 'Bottom Stitching Quality',  type: 'select',  required: true,  colIndex: 11, options: ['✅ Pass','❌ Fail'] },
    { name: 'bottom_fold_size',   label: 'Bottom Fold Size (in)',     type: 'number',  required: true,  colIndex: 12 },
    { name: 'mouth_opening',      label: 'Mouth Opening (in)',        type: 'number',  required: true,  colIndex: 13 },
    { name: 'req_bag_weight',     label: 'Req. Bag Weight',           type: 'number',  required: false, colIndex: 14 },
    { name: 'bag_weight_gms',     label: 'Bag Weight (gms)',          type: 'number',  required: true,  colIndex: 15 },
    { name: 'bopp_air_gaps',      label: 'BOPP Air Gaps',             type: 'select',  required: false, colIndex: 16, options: ['No','Yes'] },
    { name: 'tested_nos',         label: 'Tested NOS',                type: 'number',  required: true,  colIndex: 17 },
    { name: 'operator_name',      label: 'Operator Name',             type: 'text',    required: false, colIndex: 18 },
    { name: 'contractor_name',    label: 'Contractor Name',           type: 'text',    required: false, colIndex: 19 },
    { name: 'remarks',            label: 'Remarks',                   type: 'textarea',required: false, colIndex: 20 },
    { name: 'tester_name',        label: 'Tester Name',               type: 'text',    required: true,  colIndex: 21 },
    { name: 'fail_photo_link',    label: 'Link (Fail Photo)',         type: 'text',    required: false, colIndex: 22 },
  ],
  manual_stitch_qc: [
    { name: 'date',               label: 'Date',                      type: 'date',    required: true,  colIndex: 1  },
    { name: 'time',               label: 'Time',                      type: 'time',    required: true,  colIndex: 2  },
    { name: 'code',               label: 'Code',                      type: 'text',    required: true,  colIndex: 3  },
    { name: 'shift',              label: 'Shift',                     type: 'select',  required: true,  colIndex: 7,  options: ['A','B'] },
    { name: 'machine_no',         label: 'Manual Stitching Machine No', type: 'number',required: true,  colIndex: 8  },
    { name: 'operator_name',      label: 'Operator Name',             type: 'text',    required: true,  colIndex: 9  },
    { name: 'contractor_name',    label: 'Contractor Name',           type: 'text',    required: false, colIndex: 10 },
    { name: 'stitching_type',     label: 'Stitching Type',            type: 'select',  required: true,  colIndex: 11, options: ['Hemming','Normal','Special'] },
    { name: 'bottom_fold_type',   label: 'Bottom Fold Type',          type: 'select',  required: true,  colIndex: 12, options: ['SINGLE','DOUBLE'] },
    { name: 'req_bottom_fold_width', label: 'Required Bottom Fold Width (in)', type: 'number', required: false, colIndex: 13 },
    { name: 'actual_bottom_fold_width', label: 'Actual Bottom Fold Width (in)', type: 'number', required: true, colIndex: 14 },
    { name: 'stitches_per_4in',   label: 'Number of Stitches (in 4 inch)', type: 'number', required: true, colIndex: 15 },
    { name: 'bottom_stitch_uniformity', label: 'Bottom Stitch Uniformity', type: 'select', required: true, colIndex: 16, options: ['✅ Pass','❌ Fail'] },
    { name: 'bottom_stitch_finish', label: 'Bottom Stitch Finish',    type: 'select',  required: true,  colIndex: 17, options: ['✅ Pass','❌ Fail'] },
    { name: 'thread_tension',     label: 'Bottom Thread Tension & Quality', type: 'select', required: true, colIndex: 18, options: ['✅ Pass','❌ Fail'] },
    { name: 'fold_alignment',     label: 'Fold Alignment',            type: 'select',  required: true,  colIndex: 19, options: ['✅ Pass','❌ Fail'] },
    { name: 'hemming_quality',    label: 'Hemming Stitching Quality', type: 'select',  required: true,  colIndex: 20, options: ['✅ Pass','❌ Fail'] },
    { name: 'bag_mouth_appearance', label: 'Bag Mouth Appearance',    type: 'select',  required: true,  colIndex: 21, options: ['✅ Pass','❌ Fail'] },
    { name: 'liner_handling',     label: 'Liner Handling in Stitching', type: 'select',required: false, colIndex: 22, options: ['✅ Pass','❌ Fail','N/A'] },
    { name: 'liner_length_test',  label: 'Liner Length in Bag (Mobile Test)', type: 'text', required: false, colIndex: 23 },
    { name: 'unwanted_item',      label: 'Unwanted Item in Bag',      type: 'select',  required: true,  colIndex: 24, options: ['No','Yes'] },
    { name: 'final_bag_length',   label: 'Final Bag Length',          type: 'number',  required: true,  colIndex: 25 },
    { name: 'final_bag_width',    label: 'Final Bag Width',           type: 'number',  required: true,  colIndex: 26 },
    { name: 'sample_bags_tested', label: 'Sample Bags Tested (Nos.)', type: 'number',  required: true,  colIndex: 27 },
    { name: 'bags_failed',        label: 'No. of Bags Failed',        type: 'number',  required: false, colIndex: 28 },
    { name: 'remarks',            label: 'Remarks',                   type: 'textarea',required: false, colIndex: 29 },
    { name: 'tester_name',        label: 'Tester Name',               type: 'text',    required: true,  colIndex: 30 },
    { name: 'fail_photo_link',    label: 'Link (Fail Photo)',         type: 'text',    required: false, colIndex: 31 },
  ],
};
