export const FORM_FIELDS = {
  tapeline: [
    { name: 'date',            label: 'Date',                  type: 'date',   required: true,  colIndex: 1  },
    { name: 'time',            label: 'Entry Time',            type: 'time',   required: true,  colIndex: 2  },
    { name: 'code',            label: 'Code',                  type: 'text',   required: true,  colIndex: 3  },
    { name: 'shift',           label: 'Shift',                 type: 'select', required: true,  colIndex: 6,  options: ['A','B'] },
    { name: 'operator',        label: 'Operator Name',         type: 'text',   required: true,  colIndex: 7  },
    { name: 'total_input_kg',  label: 'Total Input (kg)',      type: 'number', required: true,  colIndex: 23 },
    { name: 'start_wastage',   label: 'Starting Wastage (kg)', type: 'number', required: false, colIndex: 24 },
    { name: 'run_wastage',     label: 'Running Wastage (kg)',  type: 'number', required: false, colIndex: 25 },
    { name: 'pp_invoice',      label: 'PP Purchase Invoice No',type: 'text',   required: true,  colIndex: 27 },
    { name: 'remarks',         label: 'Remarks',               type: 'textarea',required: false,colIndex: 28 },
    { name: 'tester_name',     label: 'Tester Name',           type: 'text',   required: true,  colIndex: 29 },
    { name: 'no_production',   label: 'No Production?',        type: 'checkbox',required: false, colIndex: null },
  ],
  rolldown: [
    { name: 'date',            label: 'Date',                  type: 'date',   required: true,  colIndex: 4  },
    { name: 'loom_no',         label: 'Loom No.',              type: 'number', required: true,  colIndex: 6  },
    { name: 'shift',           label: 'Shift',                 type: 'select', required: true,  colIndex: 12, options: ['A','B'] },
    { name: 'roll_no',         label: 'Roll No.',              type: 'text',   required: true,  colIndex: 13 },
    { name: 'fabric_mtrs',     label: 'Roll Down Fabric (mtrs)',type:'number', required: true,  colIndex: 15 },
    { name: 'net_wt_kg',       label: 'Roll Net Wt. (Kg)',     type: 'number', required: true,  colIndex: 16 },
    { name: 'loom_wastage',    label: 'Loom Wastage (Kg)',     type: 'number', required: false, colIndex: 20 },
    { name: 'remarks',         label: 'Remarks',               type: 'textarea',required: false,colIndex: 21 },
    { name: 'qc_name',         label: 'QC Name',               type: 'text',   required: true,  colIndex: 22 },
  ],
  liner: [
    { name: 'date',            label: 'Date',                  type: 'date',   required: true,  colIndex: 2  },
    { name: 'time',            label: 'Entry Time',            type: 'time',   required: true,  colIndex: 3  },
    { name: 'code',            label: 'Code',                  type: 'text',   required: true,  colIndex: 4  },
    { name: 'shift',           label: 'Shift',                 type: 'select', required: true,  colIndex: 8,  options: ['A','B'] },
    { name: 'operator',        label: 'Operator Name',         type: 'text',   required: true,  colIndex: 9  },
    { name: 'machine_no',      label: 'Machine No.',           type: 'select', required: true,  colIndex: 10, options: ['1','2','3'] },
    { name: 'bis_flag',        label: 'BIS / NON-BIS',         type: 'select', required: true,  colIndex: 11, options: ['BIS','NON-BIS'] },
    { name: 'liner_color',     label: 'Liner Color',           type: 'text',   required: true,  colIndex: 12 },
    { name: 'meter_weight',    label: 'Meter Weight (gms)',    type: 'number', required: true,  colIndex: 13 },
    { name: 'width_inch',      label: 'Width (inch)',          type: 'text',   required: true,  colIndex: 14 },
    { name: 'length_inch',     label: 'Length (inch)',         type: 'text',   required: true,  colIndex: 15 },
    { name: 'lldpe_kg',        label: 'LLDPE (Kg)',            type: 'number', required: false, colIndex: 17 },
    { name: 'filler_kandui',   label: 'Filler Kandui (Kg)',    type: 'number', required: false, colIndex: 18 },
    { name: 'kandui_mouser',   label: 'Kandui Mouser (Kg)',    type: 'number', required: false, colIndex: 19 },
    { name: 'rp',              label: 'RP',                    type: 'number', required: false, colIndex: 20 },
    { name: 'mb04',            label: 'MB-04',                 type: 'number', required: false, colIndex: 21 },
    { name: 'ldpe_kg',         label: 'LDPE (Kg)',             type: 'number', required: false, colIndex: 22 },
    { name: 'tpt_kg',          label: 'TPT (Kg)',              type: 'number', required: false, colIndex: 23 },
    { name: 'liner_wastage',   label: 'Liner Wastage (kg)',    type: 'number', required: false, colIndex: 24 },
    { name: 'remarks',         label: 'Remarks',               type: 'textarea',required: false,colIndex: 26 },
    { name: 'tester_name',     label: 'Tester Name',           type: 'text',   required: true,  colIndex: 27 },
  ],
  printing: [
    { name: 'date',            label: 'Date',                  type: 'date',   required: true,  colIndex: 2  },
    { name: 'time',            label: 'Entry Time',            type: 'time',   required: true,  colIndex: 3  },
    { name: 'shift',           label: 'Shift',                 type: 'select', required: true,  colIndex: 8,  options: ['A','B'] },
    { name: 'machine_name',    label: 'Machine Name',          type: 'select', required: true,  colIndex: 9,  options: ['PNRM','JP Online'] },
    { name: 'operator',        label: 'Operator',              type: 'text',   required: true,  colIndex: 10 },
    { name: 'roll_no',         label: 'Roll No.',              type: 'text',   required: true,  colIndex: 12 },
    { name: 'print_wastage',   label: 'Printing Wastage (bags)',type:'number', required: false, colIndex: 16 },
    { name: 'ink_wastage',     label: 'Ink Wastage',           type: 'number', required: false, colIndex: 17 },
    { name: 'reducer_wastage', label: 'Reducer Wastage',       type: 'number', required: false, colIndex: 18 },
    { name: 'test_bags',       label: 'Test Printing Bags (Nos)',type:'number',required: false, colIndex: 19 },
    { name: 'remarks',         label: 'Remarks',               type: 'textarea',required: false,colIndex: 21 },
    { name: 'qc_name',         label: 'QC Name',               type: 'text',   required: true,  colIndex: 22 },
    { name: 'issue_date',      label: 'Date of Issue',         type: 'date',   required: false, colIndex: 23 },
    { name: 'issue_to_bcs',    label: 'Issue to BCS Machine No',type:'number', required: false, colIndex: 24 },
  ],
  bopp: [
    { name: 'date',            label: 'Date',                  type: 'date',   required: true,  colIndex: 2  },
    { name: 'time',            label: 'Entry Time',            type: 'time',   required: true,  colIndex: 3  },
    { name: 'shift',           label: 'Shift',                 type: 'select', required: true,  colIndex: 8,  options: ['A','B'] },
    { name: 'operator',        label: 'Operator Name',         type: 'text',   required: true,  colIndex: 9  },
    { name: 'roll_no',         label: 'Roll No.',              type: 'text',   required: true,  colIndex: 11 },
    { name: 'gross_weight',    label: 'Gross Weight (Kg)',      type: 'number', required: true,  colIndex: 13 },
    { name: 'final_lam_mtrs',  label: 'Final Laminated Fabric (Mtrs)',type:'number',required:true,colIndex:17},
    { name: 'lam_wastage',     label: 'Lamination Wastage (kg)',type:'number', required: false, colIndex: 18 },
    { name: 'pp_h3050',        label: 'PP H3050 EC (Kg)',       type: 'number', required: false, colIndex: 19 },
    { name: 'la17',            label: 'LA.17.1070 (Kg)',        type: 'number', required: false, colIndex: 20 },
    { name: 'r7330',           label: '7330 (Kg)',              type: 'number', required: false, colIndex: 21 },
    { name: 'uv_kg',           label: 'U.V (Kg)',               type: 'number', required: false, colIndex: 22 },
    { name: 'kandui_filler',   label: 'Kandui Filler (Kg)',     type: 'number', required: false, colIndex: 23 },
    { name: 'bopp_rolls_nos',  label: 'BOPP Roll Used (Nos)',   type: 'number', required: false, colIndex: 24 },
    { name: 'bopp_roll_wt',    label: 'BOPP Roll Weight (Kg)',  type: 'number', required: false, colIndex: 25 },
    { name: 'bopp_wastage',    label: 'BOPP Wastage',           type: 'number', required: false, colIndex: 26 },
    { name: 'test_bags',       label: 'Test Bags (Nos)',         type: 'number', required: false, colIndex: 27 },
    { name: 'remarks',         label: 'Remarks',                type: 'textarea',required:false, colIndex: 28 },
    { name: 'qc_name',         label: 'QC Name',                type: 'text',  required: true,  colIndex: 29 },
    { name: 'issue_date',      label: 'Date of Issue',          type: 'date',  required: false, colIndex: 30 },
    { name: 'issue_to_bcs',    label: 'Issue to BCS Machine No',type:'number', required: false, colIndex: 31 },
  ],
  bcs: [
    { name: 'date',            label: 'Date',                   type: 'date',  required: true,  colIndex: 3  },
    { name: 'time',            label: 'Entry Time',             type: 'time',  required: true,  colIndex: 4  },
    { name: 'code',            label: 'Code',                   type: 'text',  required: true,  colIndex: 5  },
    { name: 'shift',           label: 'Shift',                  type: 'select',required: true,  colIndex: 10, options: ['A','B'] },
    { name: 'operator',        label: 'Operator Name',          type: 'text',  required: true,  colIndex: 11 },
    { name: 'contractor',      label: 'Contractor Name',        type: 'text',  required: true,  colIndex: 12 },
    { name: 'bcs_machine_no',  label: 'BCS Machine Number',     type: 'number',required: true,  colIndex: 13 },
    { name: 'roll_no',         label: 'Roll No.',               type: 'text',  required: true,  colIndex: 14 },
    { name: 'bags_produced',   label: 'Bags Produced (Nos.)',   type: 'number',required: true,  colIndex: 16 },
    { name: 'bcs_wastage',     label: 'BCS Wastage (Nos)',      type: 'number',required: false, colIndex: 18 },
    { name: 'loom_damaged',    label: 'Loom Damaged Bags (Nos)',type: 'number',required: false, colIndex: 19 },
    { name: 'print_damaged',   label: 'Print/BOPP/Lam Damaged', type: 'number',required: false, colIndex: 20 },
    { name: 'blade_cut',       label: 'Blade Cut Damaged (Nos)',type: 'number',required: false, colIndex: 21 },
    { name: 'repairable',      label: 'Repairable Bags (Nos)', type: 'number',required: false, colIndex: 22 },
    { name: 'remarks',         label: 'Remarks',                type:'textarea',required:false, colIndex: 25 },
    { name: 'tester_name',     label: 'Tester Name',            type: 'text',  required: true,  colIndex: 26 },
  ],
  baling: [
    { name: 'date',            label: 'Date',                   type: 'date',  required: true,  colIndex: 2  },
    { name: 'time',            label: 'Entry Time',             type: 'time',  required: true,  colIndex: 3  },
    { name: 'code',            label: 'Code',                   type: 'text',  required: true,  colIndex: 4  },
    { name: 'no_of_bale',      label: 'No. of Bale',            type: 'number',required: true,  colIndex: 9  },
    { name: 'extra_bags',      label: 'Extra Bags in Bale',     type: 'number',required: false, colIndex: 10 },
    { name: 'remarks',         label: 'Remarks',                type:'textarea',required:false, colIndex: 12 },
    { name: 'contractor_name', label: 'Contractor Name',        type: 'text',  required: true,  colIndex: 13 },
    { name: 'qc_name',         label: 'QC Name',                type: 'text',  required: true,  colIndex: 14 },
  ],
};
